import PDFDocument from 'pdfkit';

export interface ChecklistTaskPdf {
  label: string;
  completed: boolean;
}

export interface JobReportPdfData {
  companyName: string;
  clientName: string;
  address?: string;
  scheduledAt: string;
  notes?: string;
  checklist?: { template_name: string; tasks: ChecklistTaskPdf[] };
  beforePhotoCount: number;
  afterPhotoCount: number;
  reportUrl?: string;
}

/** Generate PDF buffer for a job service report (public share). */
export function generateJobReportPdf(data: JobReportPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(18).font('Helvetica-Bold').text('Service Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('#10b981').text('Status: Completed', { align: 'center' });
    doc.fillColor('#000000').moveDown(2);

    doc.fontSize(10).font('Helvetica-Bold').text('Company', 50, doc.y);
    doc.font('Helvetica').text(data.companyName || '—');
    doc.moveDown(1);

    doc.font('Helvetica-Bold').text('Customer', 50, doc.y);
    doc.font('Helvetica').text(data.clientName || '—');
    doc.moveDown(0.5);
    if (data.address) {
      doc.fontSize(9).text(data.address, 50, doc.y, { width: 500 });
      doc.moveDown(1);
    } else doc.moveDown(0.5);

    doc.fontSize(10).font('Helvetica-Bold').text('Completion date', 50, doc.y);
    doc.font('Helvetica').text(data.scheduledAt || '—');
    doc.moveDown(1.5);

    if (data.notes?.trim()) {
      doc.font('Helvetica-Bold').text('Service summary', 50, doc.y);
      doc.font('Helvetica').fontSize(9).text(data.notes, 50, doc.y + 14, { width: 500 });
      doc.moveDown(2);
    }

    if (data.checklist?.tasks?.length) {
      doc.font('Helvetica-Bold').text('Tasks completed', 50, doc.y);
      doc.font('Helvetica').fontSize(9).text(`${data.checklist.template_name} · ${data.checklist.tasks.filter((t) => t.completed).length}/${data.checklist.tasks.length} completed`, 50, doc.y + 12);
      doc.moveDown(0.8);
      data.checklist.tasks.forEach((t) => {
        const mark = t.completed ? '✓' : '—';
        doc.font('Helvetica').fontSize(9).text(`${mark}  ${t.label}`, 50, doc.y, { width: 500 });
        doc.moveDown(0.4);
      });
      doc.moveDown(1.5);
    }

    doc.font('Helvetica-Bold').text('Visual verification', 50, doc.y);
    doc.font('Helvetica').fontSize(9).text(
      `Before photos: ${data.beforePhotoCount} · After photos: ${data.afterPhotoCount}`,
      50,
      doc.y + 12
    );
    if (data.reportUrl) {
      doc.fontSize(8).fillColor('#6366f1').text(`Full report: ${data.reportUrl}`, 50, doc.y + 24, { width: 500 });
      doc.fillColor('#000000');
    }
    doc.moveDown(3);
    doc.font('Helvetica').fontSize(8).fillColor('#666').text('Generated by CleanPro · Digital service report', 50, doc.y);
    doc.end();
  });
}
